name: iOS CI

on:
  push:
    branches: [ develop ] # Assuming feature branch is develop
  pull_request:
    branches: [ develop ]

jobs:
  build_and_test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Select Xcode Version
      uses: actions/setup-xcode@v2
      with:
        xcode-version: '15.x' # Or specific version like '15.2'

    - name: Cache Tuist Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.tuist
          .tuist-build
          .build
        key: ${{ runner.os }}-tuist-${{ hashFiles('**/Project.swift', '**/Tuist.swift') }}
        restore-keys: |
          ${{ runner.os }}-tuist-

    - name: Install Tuist
      run: curl -Ls https://install.tuist.io | bash

    - name: Tuist Generate
      run: tuist generate

    - name: Build and Test
      run: xcodebuild clean build test -project DripNote.xcodeproj -scheme DripNote -destination 'platform=iOS Simulator,name=iPhone 15' | xcpretty
      # -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' # Example
